version: "3.8"
services:
  copter:
    environment:
      - MAVLINK_HOSTNAME=mavgw3
    image: arthurrichards77/ardupilot-sitl-docker:v4
    deploy:
      mode: replicated
      replicas: 3
  mavgw:
    image: arthurrichards77/mavrouter:v1
    container_name: mavgw3
    command: mavlink-routerd 0.0.0.0:14553
    ports:
      - "5760:5760"
  redis:
    image: redis:alpine
