version: "3.8"
services:
  copter:
    environment:
      - MAVLINK_OUT=mavgw:14553
    build: .
    command: bash
  mavgw:
    build: .
    container_name: mavgw
    command: mavlink-routerd 0.0.0.0:14553
    ports:
      - "5760:5760"
