services:
  copter_1:
    entrypoint: sh /app/copter_1.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
  copter_2:
    entrypoint: sh /app/copter_2.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
  copter_3:
    entrypoint: sh /app/copter_3.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
  copter_4:
    entrypoint: sh /app/copter_4.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
  mavgw:
    depends_on:
    - copter_1
    - copter_2
    - copter_3
    - copter_4
    - quadplane_5
    entrypoint: sh /app/gw_launch_4.sh
    image: mickeyli789/mavlink-router
    ports:
    - 5760:5760
    volumes:
    - ./app:/app
  quadplane_5:
    entrypoint: sh /app/quadplane_5.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
version: '3.8'
