services:
  copter_1:
    entrypoint: sh /app/copter_1.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
  copter_2:
    entrypoint: sh /app/copter_2.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
  quadplane_3:
    entrypoint: sh /app/quadplane_3.sh
    image: murphy360/ardupilot-sitl-copter
    volumes:
    - ./app:/app
  mavgw:
    entrypoint: sh /app/gw_launch.sh
    depends_on:
    - copter_1
    - copter_2
    - quadplane_3
    image: mickeyli789/mavlink-router
    ports:
    - 5760:5760
    volumes:
    - ./app:/app
version: '3.8'
